datatreasury:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: datatreasury
      schema: silver
      threads: 4
      keepalives_idle: 0
