version: 2

models:
  - name: mart_macro_daily
    description: "Daily macroeconomic indicators (SELIC, IPCA, USDBRL) in gold layer."
    columns:
      - name: date
        description: "Reference date."
        tests:
          - not_null
          - unique

  - name: mart_prices_daily
    description: "Daily asset prices (e.g. crypto, FX) in gold layer."
    columns:
      - name: symbol
        description: "Asset symbol, e.g., BTC, ETH, USDBRL."
        tests:
          - not_null
      - name: date
        description: "Reference date."
        tests:
          - not_null
